language: python
python:
 - "2.7"
virtualenv:
  system_site_packages: true
install:
 - "sudo apt-get --no-install-recommends install python-sympy libhdf5-serial-dev python-numpy python-scipy python-matplotlib gfortran"
 - "mkdir -p ~/.matplotlib/; echo 'backend : Agg' > ~/.matplotlib/matplotlibrc"
 - "pip install h5py cython --use-mirrors"
 - "ls; cd depends; make libint-linux-x86_64-gcc-4.7.2; cd .."
 - "ls; cd depends; make libxc 2>&1 > make_libxc.out; cd .."
 - "cd data/refatoms; make all; cd ../.."
 - "./setup.py build_ext -i"
script:
 - "nosetests -v horton"
