language: python
python:
 - "2.6"
 - "2.7"
before_install:
 - "sudo apt-get install cython python-h5py python-numpy python-scipy python-sympy"
install: 
 - "cd depends; make libint"
 - "cd depends; make libxc"
 - "cd data/refatoms; wget http://users.ugent.be/~tovrstra/horton_refatoms.tar.bz2; tar -xvjf horton_refatoms.tar.bz2"
script: nosetests
